import { jsPDF } from "jspdf";

export const generatePdfBlob = async (content: string, title: string): Promise<Blob> => {
  const doc = new jsPDF();
  
  // Basic configuration for a scientific look
  doc.setFont("times", "roman");
  
  // Title
  doc.setFontSize(18);
  doc.text(title, 20, 20);
  
  // Metadata
  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text(`Generated by Gemini 3 Pro - Deep Research Protocol`, 20, 28);
  doc.text(`Date: ${new Date().toLocaleDateString()}`, 20, 33);
  
  // Content
  doc.setTextColor(0);
  doc.setFontSize(11);
  doc.setLineHeightFactor(1.5);
  
  // Simple clean up of markdown symbols for PDF readability
  // Note: For a robust app, we would use a HTML renderer, but for this prototype
  // we strip basic markdown to keep it clean.
  const cleanContent = content
    .replace(/\*\*/g, "") // Bold
    .replace(/##/g, "")   // Headers
    .replace(/\[Visual Entity:.*?\]/g, "[Figure Reference]") // simplify visual tags
    .replace(/<reasoning>[\s\S]*?<\/reasoning>/g, "") // Remove internal reasoning logs if present in text
    .trim();

  const splitText = doc.splitTextToSize(cleanContent, 170); // 170mm width
  
  let cursorY = 45;
  
  splitText.forEach((line: string) => {
    if (cursorY > 280) {
      doc.addPage();
      cursorY = 20;
    }
    doc.text(line, 20, cursorY);
    cursorY += 6;
  });

  return doc.output('blob');
};